# Explicitly set Node.js as the provider
[providers]
node = "20"

[phases.setup]
nixPkgs = ["nodejs_20", "typescript", "nodePackages.typescript"]

[phases.install]
cmds = [
  "npm install -g typescript @types/node",
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm run start"
